ALTER SESSION SET CURRENT_SCHEMA = APP_DATA;

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE HD_TICKET_COMMENTS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE HD_TICKETS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE HD_ASSETS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE HD_USERS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE HD_DEPARTMENTS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE HD_DEPARTMENTS (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    location VARCHAR2(100)
);

CREATE TABLE HD_USERS (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) NOT NULL UNIQUE,
    email VARCHAR2(100) NOT NULL UNIQUE,
    department_id NUMBER REFERENCES HD_DEPARTMENTS(id),
    role VARCHAR2(20) DEFAULT 'USER' CHECK (role IN ('ADMIN', 'IT', 'USER'))
);

CREATE TABLE HD_ASSETS (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    asset_tag VARCHAR2(50) NOT NULL UNIQUE,
    device_type VARCHAR2(50) NOT NULL,
    model VARCHAR2(100),
    assigned_user_id NUMBER REFERENCES HD_USERS(id),
    status VARCHAR2(20) DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'BROKEN', 'LOST', 'RETIRED'))
);

CREATE TABLE HD_TICKETS (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    title VARCHAR2(200) NOT NULL,
    description CLOB,
    status VARCHAR2(20) DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'IN_PROGRESS', 'WAITING', 'CLOSED')),
    priority VARCHAR2(20) DEFAULT 'MEDIUM' CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    created_by NUMBER REFERENCES HD_USERS(id),
    assigned_to NUMBER REFERENCES HD_USERS(id),
    asset_id NUMBER REFERENCES HD_ASSETS(id),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    ai_summary CLOB
);

CREATE TABLE HD_TICKET_COMMENTS (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    ticket_id NUMBER REFERENCES HD_TICKETS(id) ON DELETE CASCADE,
    user_id NUMBER REFERENCES HD_USERS(id),
    comment_text CLOB NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

DECLARE
    TYPE t_names IS VARRAY(10) OF VARCHAR2(50);
    v_first_names t_names := t_names('Jan', 'Piet', 'Klaas', 'Marie', 'Sophie', 'Lisa', 'Tim', 'Tom', 'Emma', 'Julia');
    v_last_names t_names := t_names('Jansen', 'De Vries', 'Bakker', 'Visser', 'Smit', 'Meijer', 'Boer', 'De Groot', 'Vos', 'Peters');
    
    v_dept_count NUMBER := 5;
    v_user_count NUMBER := 50;
    v_asset_count NUMBER := 100;
    v_ticket_count NUMBER := 200;
    
    v_user_id NUMBER;
    v_dept_id NUMBER;
    v_asset_id NUMBER;
    v_ticket_id NUMBER;
    
    v_name VARCHAR2(100);
BEGIN
    -- Departments
    INSERT INTO HD_DEPARTMENTS (name, location) VALUES ('IT Support', 'Amsterdam HQ');
    INSERT INTO HD_DEPARTMENTS (name, location) VALUES ('Sales', 'Rotterdam Office');
    INSERT INTO HD_DEPARTMENTS (name, location) VALUES ('Marketing', 'Amsterdam HQ');
    INSERT INTO HD_DEPARTMENTS (name, location) VALUES ('HR', 'Utrecht Branch');
    INSERT INTO HD_DEPARTMENTS (name, location) VALUES ('Finance', 'Amsterdam HQ');

    -- Users
    FOR i IN 1..v_user_count LOOP
        v_name := v_first_names(TRUNC(DBMS_RANDOM.VALUE(1, 11))) || ' ' || v_last_names(TRUNC(DBMS_RANDOM.VALUE(1, 11))) || i;
        v_dept_id := TRUNC(DBMS_RANDOM.VALUE(1, 6));
        INSERT INTO HD_USERS (username, email, department_id, role)
        VALUES (
            REPLACE(LOWER(v_name), ' ', '.'),
            REPLACE(LOWER(v_name), ' ', '.') || '@bedrijf.nl',
            v_dept_id,
            CASE WHEN i <= 5 THEN 'IT' WHEN i = 6 THEN 'ADMIN' ELSE 'USER' END
        );
    END LOOP;

    -- Assets
    FOR i IN 1..v_asset_count LOOP
        v_user_id := TRUNC(DBMS_RANDOM.VALUE(1, v_user_count + 1));
        INSERT INTO HD_ASSETS (asset_tag, device_type, model, assigned_user_id, status)
        VALUES (
            'TAG-' || LPAD(i, 5, '0'),
            CASE TRUNC(DBMS_RANDOM.VALUE(1, 4)) WHEN 1 THEN 'Laptop' WHEN 2 THEN 'Phone' ELSE 'Monitor' END,
            CASE TRUNC(DBMS_RANDOM.VALUE(1, 4)) WHEN 1 THEN 'Dell XPS' WHEN 2 THEN 'MacBook Pro' ELSE 'iPhone 15' END,
            CASE WHEN DBMS_RANDOM.VALUE(0, 1) > 0.2 THEN v_user_id ELSE NULL END,
            CASE TRUNC(DBMS_RANDOM.VALUE(1, 10)) WHEN 1 THEN 'BROKEN' WHEN 2 THEN 'LOST' ELSE 'ACTIVE' END
        );
    END LOOP;

    -- Tickets
    FOR i IN 1..v_ticket_count LOOP
        v_user_id := TRUNC(DBMS_RANDOM.VALUE(6, v_user_count + 1)); 
        v_asset_id := TRUNC(DBMS_RANDOM.VALUE(1, v_asset_count + 1));
        INSERT INTO HD_TICKETS (title, description, status, priority, created_by, assigned_to, asset_id, created_at)
        VALUES (
            'Probleem met ' || CASE TRUNC(DBMS_RANDOM.VALUE(1, 5)) WHEN 1 THEN 'Muis' WHEN 2 THEN 'Laptop' WHEN 3 THEN 'Scherm' ELSE 'Software' END,
            'Hallo IT, mijn apparaat doet de laatste tijd heel erg raar. Het scherm valt soms uit en programma''s starten langzaam op. Kunnen jullie hiernaar kijken? Bedankt alvast!',
            CASE TRUNC(DBMS_RANDOM.VALUE(1, 5)) WHEN 1 THEN 'OPEN' WHEN 2 THEN 'IN_PROGRESS' WHEN 3 THEN 'WAITING' ELSE 'CLOSED' END,
            CASE TRUNC(DBMS_RANDOM.VALUE(1, 5)) WHEN 1 THEN 'LOW' WHEN 2 THEN 'MEDIUM' WHEN 3 THEN 'HIGH' ELSE 'CRITICAL' END,
            v_user_id,
            CASE WHEN DBMS_RANDOM.VALUE(0, 1) > 0.5 THEN TRUNC(DBMS_RANDOM.VALUE(1, 6)) ELSE NULL END, 
            CASE WHEN DBMS_RANDOM.VALUE(0, 1) > 0.5 THEN v_asset_id ELSE NULL END,
            SYSTIMESTAMP - NUMTODSINTERVAL(DBMS_RANDOM.VALUE(1, 30), 'DAY')
        ) RETURNING id INTO v_ticket_id;

        -- Comments
        FOR j IN 1..TRUNC(DBMS_RANDOM.VALUE(0, 4)) LOOP
            INSERT INTO HD_TICKET_COMMENTS (ticket_id, user_id, comment_text)
            VALUES (
                v_ticket_id,
                CASE WHEN MOD(j, 2) = 0 THEN v_user_id ELSE TRUNC(DBMS_RANDOM.VALUE(1, 6)) END,
                'Reactie ' || j || ' op dit ticket. We zijn er mee bezig.'
            );
        END LOOP;
    END LOOP;
    COMMIT;
END;
/
exit;
